//common
export const LOADING = 'LOADING';
export const CODE_ERROR = 'CODE_ERROR';
//auth
export const RESTART_AUTH_RESPONSE = 'RESTART_AUTH_RESPONSE';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';
//profile
export const LOAD_PROFILE_SUCCESS = 'LOAD_PROFILE_SUCCESS';
export const LOAD_PROFILE_ERROR = 'LOAD_PROFILE_ERROR';
export const CART_ITEM_ADDED = 'CART_ITEM_ADDED';
export const CHECK_ADDED_SUCCESS =  'CHECK_ADDED_SUCCESS';
export const LOAD_PRODUCTS_SUCCESS = 'LOAD_PRODUCTS_SUCCESS';
export const LOAD_PRODUCT_SUCCESS = 'LOAD_PRODUCT_SUCCESS';