version: "3.8"
services: 

  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ports:
        - 3306:3306
    environment:
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: 1
      # MYSQL_ALLOW_EMPTY_PASSWORD: yes
    volumes:
      - ./initDB:/docker-entrypoint-initdb.d
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOSTS: db
      PMA_PORT: 3306
    depends_on:
      - db

  express:
    # build: ./Express
    image: tzacheilas/express:1.1
    depends_on:
      db:
        condition: service_healthy
    env_file: ./Express/.env
    ports:
      - 5000:5000
    stdin_open: true
    tty: true

  laravel:
    # build: ./Laravel
    image: tzacheilas/laravel:1.1
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
    env_file: ./Laravel/.env
    stdin_open: true
    tty: true
    entrypoint: sh -c "php artisan migrate && php artisan db:seed --class=DatabaseSeeder && php artisan serve --host 0.0.0.0"

  react:
    # build: ./client-side
    image: tzacheilas/react:1.1
    env_file: ./client-side/.env
    ports:
      - 3001:3000
    stdin_open: true
    tty: true

# networks:
#   mysite:
# network_mode: 'host'

# healthcheck:
#   test: ["CMD", "curl", "http://localhost:4001"]
#   interval: 30s
#   timeout: 10s
#   retries: 5

# volumes: 
#   db-config:
#   db-data: